[package]
name = "lasercube-core"
version = "0.1.0"
description = "A library providing high-level interfaces for discovering and controlling LaserCube devices"
edition.workspace = true
license.workspace = true

[dependencies]
bitflags.workspace = true
thiserror.workspace = true
